"use client";

import { CreditCard, ExternalLink, Loader2 } from "lucide-react";
import { useGetLatestPaymentsQuery } from "@/redux/api/accountsApi";

export default function LatestPaymentsPage() {
    const { data: payments = [], isLoading } = useGetLatestPaymentsQuery();
    return <div className="space-y-6"><div className="flex items-center gap-3"><div className="rounded-xl bg-orange-600 p-3 text-white"><CreditCard /></div><div><h1 className="text-3xl font-bold text-slate-800">Latest Payments</h1><p className="text-slate-500">Payments received during the latest 10 calendar days.</p></div></div><div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-4">Received</th><th className="px-5 py-4">Student</th><th className="px-5 py-4">Class / months</th><th className="px-5 py-4">Annual</th><th className="px-5 py-4">Amount</th><th className="px-5 py-4">Mode</th><th className="px-5 py-4">Receipt</th></tr></thead><tbody className="divide-y divide-slate-100">{isLoading ? <tr><td colSpan={7} className="p-12 text-center"><Loader2 className="mx-auto animate-spin text-orange-600" /></td></tr> : payments.length === 0 ? <tr><td colSpan={7} className="p-12 text-center text-slate-500">No payments have been received in the latest 10 days.</td></tr> : payments.map((payment) => <tr key={payment.id} className="hover:bg-orange-50/40"><td className="px-5 py-4 text-slate-600">{new Date(payment.paidAt).toLocaleString("en-IN")}</td><td className="px-5 py-4"><p className="font-semibold text-slate-800">{payment.student.fullName}</p><p className="text-xs text-slate-500">{payment.student.admissionNumber}</p></td><td className="px-5 py-4 text-slate-600">{payment.student.classroomName}<br /><span className="text-xs">{payment.monthsPaid}</span></td><td className="px-5 py-4">₹{payment.annualContribution.toLocaleString("en-IN")}</td><td className="px-5 py-4 font-bold text-slate-900">₹{payment.amountPaid.toLocaleString("en-IN")}</td><td className="px-5 py-4"><span className="rounded-full bg-emerald-100 px-2 py-1 text-xs font-bold text-emerald-800">{payment.paymentMode ?? "—"}</span></td><td className="px-5 py-4">{payment.receiptUrl ? <a href={payment.receiptUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-orange-700 hover:underline">View <ExternalLink size={14} /></a> : "—"}</td></tr>)}</tbody></table></div></div></div>;
}
